M48
; DRILL file {KiCad 7.0.7} date 2023 August 23, Wednesday 23:36:49
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-23T23:36:49-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X4.6732Y-4.5551
X8.5906Y-4.9567
X8.5945Y-1.5906
T2
X9.5481Y-4.8567
X9.5481Y-5.0535
T3
X9.4925Y-2.4089
X9.768Y-2.4089
T4
X7.0433Y-1.7441
X7.0433Y-4.8441
T0
M30
