M48
; DRILL file {KiCad 7.0.6-0} date 2023 July 28, Friday 21:35:03
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-28T21:35:03-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
%
G90
G05
T1
X5.4439Y-2.5118
X5.6407Y-2.5118
T2
X4.748Y-5.1063
X5.0197Y-2.3346
X5.5394Y-2.6654
T3
X5.4427Y-4.9366
X5.4427Y-5.1334
T0
M30
