M48
; DRILL file {KiCad 7.0.5-0} date 2023 June 30, Friday 21:05:24
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-30T21:05:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X5.4439Y-2.5118
X5.6407Y-2.5118
T2
X5.4427Y-4.9366
X5.4427Y-5.1334
T0
M30
