#!/usr/bin/env python3
"""
Generates tll_table_flash.c for the EMU8950 OPL2 emulator.
Pre-computes makeTllTable() so the result can be stored in RP2040 flash (XIP)
instead of RAM, working around the 128KB RAM constraint.

Replicates the EMU8950_NO_FLOAT integer path from emu8950.c:
  kl_tablex16[fnum] = (uint16_t)(kl_values[fnum] * 32)
  dB2x16(3.000)     = 96
  EG_STEPx16        = 3
  TL2EG(tl)         = tl << 2
"""

TL_BITS = 6
EG_STEPx16 = 3

kl_values = [
    0.000,  9.000, 12.000, 13.875, 15.000, 16.125,
   16.875, 17.625, 18.000, 18.750, 19.125, 19.500,
   19.875, 20.250, 20.625, 21.000,
]
kl_tablex16 = [int(v * 32) & 0xFFFF for v in kl_values]  # uint16_t cast
dB2x16_3 = int(3.000 * 32)  # = 96

def TL2EG(tl):
    return tl << 2

# Build table[128][64][4]
table = [[[0] * 4 for _ in range(1 << TL_BITS)] for _ in range(8 * 16)]

for fnum in range(16):
    for block in range(8):
        idx = (block << 4) | fnum
        for TL in range(1 << TL_BITS):
            for KL in range(4):
                if KL == 0:
                    table[idx][TL][KL] = TL2EG(TL)
                else:
                    kx = ((KL & 1) << 1) | ((KL >> 1) & 1)
                    tmp = kl_tablex16[fnum] - dB2x16_3 * (7 - block)
                    if tmp <= 0:
                        table[idx][TL][KL] = TL2EG(TL)
                    else:
                        table[idx][TL][KL] = (tmp >> (3 - kx)) // EG_STEPx16 + TL2EG(TL)

lines = []
lines.append("/* Auto-generated by gen_tll_table.py — do not edit manually. */")
lines.append("/* Pre-computed EMU8950 TLL (Total Level Lookup) table for RP2040 flash (XIP). */")
lines.append("/* Replicates makeTllTable() integer path; stored as const in .flashdata section so")
lines.append(" * pico-sdk copy_to_ram linker scripts keep it in flash rather than copying to RAM. */")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("/* __attribute__((section(\".flashdata.tll_table\"))) keeps this in flash even in")
lines.append(" * copy_to_ram builds (both memmap_copy_to_ram.ld and fw_memmap_c2ram.ld capture")
lines.append(" * .flashdata* into the FLASH .rodata region, not the RAM .data region). */")
lines.append("const uint32_t __attribute__((section(\".flashdata.tll_table\")))")
lines.append("    tll_table[128][64][4] = {")
for i in range(128):
    lines.append("    { /* blk_fnum=" + str(i) + " */")
    for j in range(64):
        row = ", ".join(str(table[i][j][k]) for k in range(4))
        lines.append("        {" + row + "},")
    lines.append("    },")
lines.append("};")

import os
out_path = os.path.join(os.path.dirname(__file__), "tll_table_flash.c")
with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written {len(table) * 64 * 4} uint32_t values to {out_path}")
